### ISSUE TITLE
Please check rewrite of status quo payoffs description

### ISSUE THREAD

**Issue by kbuzard** [kbuzard/UnrecognizedStates#1]
Ben, please take a look at the two paragraphs in which I rewrote the description of the status quo payoffs as a state variable and let me know how it reads to you. (this hash should take you to the commit: 6221189d68d3170426a259cc22be3ff5d7228f85)

**Comment by benjaminagraham** [comment]
Looks good!  In the footnote, secessionists' needs the possessive apostrophe added, but substantively all seems clear and in order.
